defaults:
  - model_checkpoint
  - early_stopping
  - model_summary
  - rich_progress_bar
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}-{validation_loss:.4f}"
  # monitor: "val/acc" 
  monitor: "validation_loss"
  mode: "max"
  save_last: True
  auto_insert_metric_name: False

early_stopping:
  # monitor: "val/acc"
  monitor: "validation_loss"
  # patience: 100
  patience: 15
  mode: "max"

model_summary:
  max_depth: -1
